---
- name: "rgw_exporter | Deploy rgw_exporter service configuration"
  ansible.builtin.template:
    src: "radosgw_usage_exporter.j2"
    dest: "{{ '/etc/systemd/system/' +
      hostvars[inventory_hostname]['rgw_exporter_service'] }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "Daemon reload"
    - "Restart rgw_exporter"
- name: "rgw_exporter | Enable rgw_exporter"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['rgw_exporter_service'] }}"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['radosgw_usage_exporter'] is defined"
    - "hostvars[inventory_hostname]['radosgw_usage_exporter'] != ''"
    - "hostvars[inventory_hostname]['radosgw_usage_exporter'] |
       community.general.json_query(vars['rgw_exporter_enable']) is defined"
    - "hostvars[inventory_hostname]['radosgw_usage_exporter'] |
       community.general.json_query(vars['rgw_exporter_enable']) == 'true'"
  vars:
    rgw_exporter_enable: "[] | map(&enable || 'false', @) | [0]"
- name: "rgw_exporter | Ensure docker is run"
  ansible.builtin.systemd:
    name: "docker"
    state: "started"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['radosgw_usage_exporter'] is defined"
    - "hostvars[inventory_hostname]['radosgw_usage_exporter'] != ''"
    - "hostvars[inventory_hostname]['radosgw_usage_exporter'] |
       community.general.json_query(vars['rgw_exporter_enable']) is defined"
    - "hostvars[inventory_hostname]['radosgw_usage_exporter'] |
       community.general.json_query(vars['rgw_exporter_enable']) == 'true'"
  vars:
    rgw_exporter_enable: "[] | map(&enable || 'false', @) | [0]"
