---
- name: "rgw_exporter | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "rgw_exporter | Include packages tasks"
  ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['radosgw_usage_exporter'] is defined"
    - "hostvars[inventory_hostname]['radosgw_usage_exporter'] != ''"
- name: "rgw_exporter | Include deployment tasks"
  ansible.builtin.import_tasks:
    file: "deploy.yml"
  when:
    - "vars['rgw_exporter_settings'] is defined"
    - "vars['rgw_exporter_settings'] != ''"
