---
- name: "rgw_exporter | Assert that system manager is systemd"
  ansible.builtin.assert:
    that:
      - "hostvars[inventory_hostname]['ansible_service_mgr'] == 'systemd'"
    msg: "System manager is not systemd."
    quiet: "true"
- name: "rgw_exporter | Add the OS specific varibles"
  ansible.builtin.include_vars:
    file: "{{ hostvars[inventory_hostname]['ansible_os_family'] + '.yml' }}"
- name: "rgw_exporter | Set facts about rgw_exporter role"
  ansible.builtin.set_fact:
    rgw_exporter_version:
      "{{ hostvars[inventory_hostname]['radosgw_usage_exporter'] |
      community.general.json_query('[].version | [0]') | default('latest') }}"
    rgw_exporter_settings:
      "{{ hostvars[inventory_hostname]['radosgw_usage_exporter'] |
      community.general.json_query('[].settings[]') }}"
    rgw_exporter_port:
      "{{ hostvars[inventory_hostname]['radosgw_usage_exporter'] |
      community.general.json_query('[].settings[].port | [0]') }}"
- name: "rgw_exporter | Set facts about service port"
  ansible.builtin.set_fact:
    rgw_exporter_port: "9242"
  when:
    - "(vars['rgw_exporter_port'] is defined and
      (vars['rgw_exporter_port'] == '' or
      vars['rgw_exporter_port'] == []) or
      vars['rgw_exporter_port'] is not defined)"
