---
- name: "rgw_exporter | Assert that system manager is systemd"
  ansible.builtin.assert:
    that:
      - "hostvars[inventory_hostname]['ansible_service_mgr'] == 'systemd'"
    msg: "System manager is not systemd."
    quiet: "true"
- name: "rgw_exporter | Add the OS specific varibles"
  ansible.builtin.include_vars:
    file: "{{ hostvars[inventory_hostname]['ansible_os_family'] + '.yml' }}"
- name: "rgw_exporter | Set facts about rgw_exporter role"
  ansible.builtin.set_fact:
    rgw_exporter_package_state:
      "{{ hostvars[inventory_hostname]['radosgw_usage_exporter'] |
      community.general.json_query('[].package_state | [0]') }}"
    rgw_exporter_version:
      "{{ hostvars[inventory_hostname]['radosgw_usage_exporter'] |
      community.general.json_query('[].version | [0]') | default('latest') }}"
    rgw_exporter_settings:
      "{{ hostvars[inventory_hostname]['radosgw_usage_exporter'] |
      community.general.json_query('[].settings[]') }}"
- name: "rgw_exporter | Assert that rgw_exporter package state in valid value"
  ansible.builtin.assert:
    that:
      - "vars['rgw_exporter_package_state'] in ['present', 'latest']"
    msg: "'package_state' must be in 'present' or 'latest'."
    quiet: "true"
  when:
    - "vars['rgw_exporter_package_state'] is defined"
    - "vars['rgw_exporter_package_state'] != ''"
