---
- name: "rgw_exporter | Daemon reload"
  ansible.builtin.systemd:
    daemon_reload: "yes"
  listen: "Daemon reload"
- name: "rgw_exporter | Restart rgw_exporter"
  ansible.builtin.systemd:
    name: "{{ lookup('ansible.builtin.vars', 'rgw_exporter_service') }}"
    state: "restarted"
  listen: "Restart rgw_exporter"
  when:
    - "lookup('ansible.builtin.vars', 'radosgw_usage_exporter', default='')
      not in ['', [], '[]', None]"
    - "lookup('ansible.builtin.vars', 'radosgw_usage_exporter') |
       community.general.json_query(lookup('ansible.builtin.vars',
      'rgw_exporter_restart', default='')) == 'true'"
  vars:
    rgw_exporter_restart: "[] | map(&restart || 'false', @) | [0]"
