---
- name: "Daemon reload"
  ansible.builtin.systemd:
    daemon_reload: "yes"
- name: "Restart rgw_exporter"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['rgw_exporter_service'] }}"
    state: "restarted"
  when:
    - "hostvars[inventory_hostname]['radosgw_usage_exporter'] is defined"
    - "hostvars[inventory_hostname]['radosgw_usage_exporter'] != ''"
    - "hostvars[inventory_hostname]['radosgw_usage_exporter'] |
       community.general.json_query(vars['rgw_exporter_restart']) is defined"
    - "hostvars[inventory_hostname]['radosgw_usage_exporter'] |
       community.general.json_query(vars['rgw_exporter_restart']) == 'true'"
  vars:
    rgw_exporter_restart: "[] | map(&restart || 'false', @) | [0]"
